### ISSUE TITLE
Why is go.dev latest version v1.0.1?

### ISSUE THREAD

**Issue by anhao** [madebywelch/anthropic-go#10]
Hello,Why is go.dev latest version v1.0.1?

**Comment by madebywelch** [comment]
> Hello,Why is go.dev latest version v1.0.1?

Not sure, I can check later tonight. In meantime you can pull the latest version by appending @v2.1.0 to your go get command.

**Comment by madebywelch** [comment]
> Hello,Why is go.dev latest version v1.0.1?

go get github.com/madebywelch/anthropic-go@v2.1.0

**Comment by madebywelch** [comment]
https://pkg.go.dev/github.com/madebywelch/anthropic-go/v2
