### ISSUE TITLE
Support image(s) in user prompts

### ISSUE THREAD

**Issue by lakshmanpasala** [madebywelch/anthropic-go#19]
To implement this we need to first change `Content` in `MessagePartRequest` so that we support 

1. Array of either text and/or image content.
2. Also implement the API limits like:
   - Maximum number of images per API call (20 in this case)
   - Max size of each image (5 mb)
 
Happy to take this up.

**Comment by madebywelch** [comment]
https://github.com/madebywelch/anthropic-go/pull/20

@lakshmanpasala Can you QA this please?

**Comment by madebywelch** [comment]
This is now available in latest v2.1.9
