### ISSUE TITLE
Implement Stream

### ISSUE THREAD

**Issue by frankgreco** [madebywelch/anthropic-go#2]
The OpenAI Golang SDK has a good pattern for streaming. It would be nice to see that here as well.

**Comment by madebywelch** [comment]
good idea, streaming has been implemented

**Comment by frankgreco** [comment]
Is it? Could you point me to it? I see there's a stream request param but I don't see how we return a channel or iterator to the client to process the chunks as they're streamed in.

**Comment by frankgreco** [comment]
Oh you just added it! Wow thanks!
