### ISSUE TITLE
Error: "model claude-3-haiku-20240307 is not compatible with the completion endpoint"

### ISSUE THREAD

**Issue by MartinRepo** [madebywelch/anthropic-go#22]
**Error description**
When I run example on readme as a demo. it reported error: "model claude-3-haiku-20240307 is not compatible with the completion endpoint". I don't know if somewhere I did wrong. 

**Screenshots**
![issue](https://github.com/madebywelch/anthropic-go/assets/90629140/4833e6a3-dc57-4c3d-a187-6f84d5ecf28d)

**Environment:**
- OS: Windows
- Go version: 1.21

Thanks a lot!

**Comment by madebywelch** [comment]
Thanks for reporting. I'm out of state at the moment but will look into this as soon as I'm back!

**Comment by madebywelch** [comment]
I'm back! It looks like the readme example was using a model that isn't compatible with completions (i.e., Claude 3 Haiku). I updated the readme. The error you received was expected.
