### ISSUE TITLE
[FEATURE REQUEST] Support Anthropic calls via the Google Vertex AI

### ISSUE THREAD

**Issue by kb-sp** [madebywelch/anthropic-go#28]
**Describe the bug^H^H^Hfeature request**
(First, thanks for this module, I've been using it to great effect for the last couple of months.)

Are there plans to add the Vertex AI call path?  Conceptually, I only suggest this because it uses different infra than Anthropic's endpoints, and may provide more flexible/generous rate limiting for GCP customers.

I may take a stab at this in the background if there's nothing planned or in progress, but wanted to check first. Thx!

**Comment by madebywelch** [comment]
Hi Ken,

We don't currently have any plans to add Vertex but would love for you to take a stab at it. We have a PR right now that adds AWS Bedrock support https://github.com/madebywelch/anthropic-go/pull/25. You might be able to leverage some of the changes to easily integrate Vertex support.
