### ISSUE TITLE
Continued conversation with tool calls

### ISSUE THREAD

**Issue by 1matthewli** [madebywelch/anthropic-go#35]
A typical conversation with tool calls may look something like:
- user
- system, requests some tool calls
- tool result

I saw there is a `NewToolResultContentBlock` to add a content block for the tool result. However, it is unclear to me how to add content blocks for the tool _calls_. Sorry if I'm just missing it

**Comment by madebywelch** [comment]
Hey @1matthewli 

Does this help you?

```go
request := &anthropic.MessageRequest{
  Model:             anthropic.Claude3Opus,
  MaxTokensToSample: 1024,
  ToolChoice: &anthropic.ToolChoice{
	  Type: "auto",
  },
  Tools: []anthropic.Tool{
	  {
		  Name:        "get_weather",
		  Description: "Get the weather",
		  InputSchema: anthropic.GenerateInputSchema(&WeatherRequest{}),
	  },
  },
  Messages: []anthropic.MessagePartRequest{
	  {
		  Role: "user",
		  Content: []anthropic.ContentBlock{
			  anthropic.NewTextContentBlock("what's the weather in Charleston?"),
		  },
	  },
  },
}

response, err := anthropicClient.Message(context.Background(), request)
```

**Comment by 1matthewli** [comment]
@madebywelch Thanks for the reply! I guess I'm looking for the follow-up to the tool calls -- the message request where I send the result of the tool call back to the model, e.g I imagine something like this:
```go
request := &anthropic.MessageRequest{
  Model:             anthropic.Claude3Opus,
  MaxTokensToSample: 1024,
  ToolChoice: &anthropic.ToolChoice{
	  Type: "auto",
  },
  Tools: []anthropic.Tool{
	  {
		  Name:        "get_weather",
		  Description: "Get the weather",
		  InputSchema: anthropic.GenerateInputSchema(&WeatherRequest{}),
	  },
  },
  Messages: []anthropic.MessagePartRequest{
	  {
		  Role: "user",
		  Content: []anthropic.ContentBlock{
			  anthropic.NewTextContentBlock("what's the weather in Charleston?"),
		  },
	  },
	  {
		Role: "system",
		Content: []anthropic.ContentBlock{
			anthropic.NewTextContentBlock("<thinking>I need to call get_weather tool</thinking>"),
			anthropic.NewToolCallBlock(
				"toolu_12345", /* ID */
				"get_weather", /* Name */
				"{\"city\": \"Charleston\"}", /* Input */
			)
		},
	  },
	  {
		Role: "user",
		Content: []anthropic.ContentBlock{
			anthropic.NewToolResultContentBlock(
				"toolu_12345", /* ID */
				"The weather is 72 degrees Fahrenheit", /* Result */
				false, /* IsError */
			)
		},
	  },
  },
}

```
Basically, imagine a much longer conversation in which there is a series of tool calls and tool results. I'm looking for a way to convey to the model the fact that there were historical tool calls earlier in the conversation

**Comment by madebywelch** [comment]
Yikes. We are missing that, and apparently our tools test is setup incorrectly. I'll push that change to v3 as a minor patch. I'm also working on v4 with already includes it and some QOL updates. https://github.com/madebywelch/anthropic-go/commit/75d4d054e06d5aa3ca063c089ae3df798cc2a5a5

**Comment by madebywelch** [comment]
I pushed v3.1.0 which has anthropic#NewToolUseContentBlock https://github.com/madebywelch/anthropic-go/releases/tag/v3.1.0

**Comment by 1matthewli** [comment]
Thanks so much for the quick patch! I'll try it out tomorrow morning and let you know

**Comment by 1matthewli** [comment]
Confirmed that it works, thanks again for the quick fix!
