### ISSUE TITLE
Implement Delta for Stream

### ISSUE THREAD

**Issue by frankgreco** [madebywelch/anthropic-go#4]
@madebywelch Thank you so much for implementing the streaming feature! I just tested it out and it works (<24 after I opened the initial issue 🔥 )! 

One request I'd make is adding a `Delta` to the stream response which has the new chunk that is the "delta" of the last one. [Here](https://github.com/sashabaranov/go-openai/blob/master/chat_stream.go#L16) is how OpenAI implements it.

This feature will help with use cases where we're streaming in chunks from a backend to a frontend.

**Comment by frankgreco** [comment]
This is how I'm accomplishing it in the meantime 👇🏼 

```
prev := ""

	_, err := llm.client.Complete(&llmAnthropic.CompletionRequest{
		Prompt:            prompt,
		Model:             llmAnthropic.ClaudeV1,
		MaxTokensToSample: 25,
		Stream:            true,
	}, func(response *llmAnthropic.CompletionResponse) error {
		var delta string
		{
			if prev != "" {
				arr := strings.SplitAfter(response.Completion, prev)

				if len(arr) != 2 {
					return errors.New("could not compute delta")
				}

				delta = arr[1]

			} else {
				delta = response.Completion
			}

			prev = response.Completion
		}
		ch <- &aiv1.TaskEvent{
			Chunk: structpb.NewStringValue(delta),
			Llm:   aiv1.LLM_LLM_ANTHROPIC,
			Model: aiv1.MODEL_MODEL_ANTHROPIC_CLAUDE_V1,
		}

		return nil
	})
```

**Comment by madebywelch** [comment]
good idea, i just merged adding delta to complete streaming
