### ISSUE TITLE
Support for Claude 3.5 Haiku

### ISSUE THREAD

**Issue by h00s** [madebywelch/anthropic-go#44]
Since the latest version of the Haiku package (v3.5) was released yesterday, I would kindly request that you add support for it.

I'm also very interested in contributing to the development, so please let me know if there are any ways I can help. Thank you!

**Comment by madebywelch** [comment]
Hi h00s. Feel free to add it. I don't have time as of now. If you'd like to help out take a look at some of our issues!

**Comment by h00s** [comment]
Thank you for the very quick response! I will try to add the support and make a pull request as soon as it's done. Thank you so far for the help and response!

**Comment by pigeonlaser** [comment]
support is added: https://github.com/madebywelch/anthropic-go/pull/45

**Comment by h00s** [comment]
Thanks @pigeonlaser, beat me to it 😁 Highly appreciated!
